[package]
name = "xor_enc"
version = "0.1.0"
authors = ["Valdas Rakutis <valdas@rakutis.lt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
